### ISSUE TITLE
fancy cosmos asset description

### ISSUE THREAD

**Issue by 0xdef1cafe** [shapeshift/lib#490]
let's get a nice asset description with links throughout the app in `descriptions.json`

**Comment by decentralized-j** [comment]
Gm @0xdef1cafe ser! Cosmos description below. No links included in here because i believe it will be on the same page. if my understanding there is off, please let me know and i'll add a link to cosmos staking in that last sentence. tried to keep it short and sweet

Cosmos (ATOM) is a cryptocurrency that powers an ecosystem of blockchains designed to scale and interoperate with each other. The Cosmos vision aligns with the ShapeShift vision of a multi chain future, and enables a network of blockchains to be to communicate with each other in a decentralized manner. Cosmos is a proof-of-stake chain and allows holders to stake their ATOM to earn rewards using ShapeShift.

**Comment by decentralized-j** [comment]
Updated 1 liner below.

Cosmos (ATOM) is a proof of stake cryptocurrency that powers an ecosystem of blockchains designed to interoperate and communicate with each other in a decentralized manner.

**Comment by 0xdef1cafe** [comment]
thanks @decentralized-j - i've added this description for native cosmos at the PR linked above ^^^

what do you want to do about cosmos on osmosis? see here

https://app.shapeshift.com/assets/cosmos:osmosis-1/ibc:27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
